name: nestcare
description: "A household care and maintenance app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  responsive_sizer: ^3.3.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  lucide_icons_flutter: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope.thin.otf
          weight: 100
        - asset: assets/fonts/manrope.light.otf
          weight: 300
        - asset: assets/fonts/manrope.regular.otf
          weight: 400
        - asset: assets/fonts/manrope.medium.otf
          weight: 500
        - asset: assets/fonts/manrope.semibold.otf
          weight: 600
        - asset: assets/fonts/manrope.bold.otf
          weight: 700
        - asset: assets/fonts/manrope.extrabold.otf
          weight: 800

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/nestwash_app_icon.png"
  background_color: "#6C63FF"
  background_color_ios: "#6C63FF"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/images/icons/nestwash_app_icon.png"
  adaptive_icon_foreground_dark: "assets/images/icons/nestwash_app_icon.png"
